### PR TITLE
finished initial design

### PR DESCRIPTION
**Pull request by nandala-allan**
check out my work

### CODE REVIEW

**Comment by nandala-allan** [comment]
ive resolved the merge conflict in my code check it out

**Comment by nandala-allan** [comment]
made more change

**Comment by Ndawulajoe** [comment]
Okay thanks

**Review by othinAbbey — COMMENTED** [review]
move on

**Review by othinAbbey — COMMENTED** [review]
lets move on

**Review by othinAbbey — APPROVED** [review]
lets move on

**Review by Ndawulajoe — COMMENTED** [review]
ok cool

**Review by othinAbbey — COMMENTED** [review]
move on

**Pull request merged**
